language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
install: pip install tox-travis
script: tox
#after_success:
#  - "make coveralls"
matrix:
  allow_failures:
    - python: pypy
